/* eslint-disable max-len */
import React from 'react';

export default function TermsAndConditions() {

    return (
        <div className="document">
            <div className="document__head">Terms & Conditions</div>
            <div className="document__body">

                <h2>END USER LICENSE AGREEMENT DDIS News App</h2>
                <p>This agreement (or "Custom EULA") is a legal agreement between the person, company or organization ("You") that has licensed the software product "DDIS News App" ("Licensed Application") and the University of Zurich ("Licensor" or "Application Provider"). Licensor, not Apple, is solely responsible for the Licensed Application and its content. By installing and/or using any Licensed Application provided by the Licensor, You are confirming your acceptance of this agreement and you are agreeing to become bound by the terms of this agreement.</p>
                <p>The Licensed Application is made available through the App Store and is licensed, not sold, to you. Licensor reserves all rights in and to the Licensed Application not expressly granted to you under this Custom EULA.</p>
                <p>a. Scope of License: Licensor grants you a limited, non-exclusive, non-transferable, revocable license to use the Licensed Application for your personal, non-commercial purposes. You may only use the Licensed Application on a Apple-branded products that you own or control and as permitted by the Apple App Store Terms of Service. The terms of this Custom EULA will govern any content, materials, or services accessible from or purchased within the Licensed Application as well as upgrades provided by Licensor that replace or supplement the original Licensed Application. You may not distribute or make the Licensed Application available over a network where it could be used by multiple devices at the same time. You may not transfer, redistribute or sublicense the Licensed Application and, if you sell your Apple Device to a third party, you must remove the Licensed Application from the Apple Device before doing so. You may not copy reverse-engineer, disassemble, attempt to derive the source code of, modify, or create derivative works of the Licensed Application, any updates, or any part thereof (except as and only to the extent that any foregoing restriction is prohibited by applicable law).</p>
                <p>b. Consent to Use of Data: Licensor may collect and use information about your usage of the Licensed Application, including certain types of information from and about your device. Licensor may use this information, as long as it is in a form that does not personally identify you, to measure the use and performance of the Licensed Application.</p>
                <p>c. Licensor does not provide any maintenance or support for the Licensed Application. To the extent that any maintenance or support is required by applicable law, Licensor, not Apple, shall be obligated to furnish any such maintenance or support.</p>
                <p>d. Termination. This Custom EULA is effective until terminated by you or Licensor. Your rights under this Custom EULA will terminate automatically if you fail to comply with any of its terms. Upon termination of the license, You shall cease all use of the Licensed Application, and destroy all copies, full or partial, of the Licensed Application.</p>
                <p>e. External Services. The Licensed Application may enable access to Licensor's and/or third-party services and websites (collectively and individually, "External Services"). You agree to use the External Services at your sole risk. Licensor is not responsible for examining or evaluating the content or accuracy of any third-party External Services, and shall not be liable for any such third-party External Services. Data displayed by any Licensed Application or External Service, including but not limited to financial, medical and location information, is for general informational purposes only and is not guaranteed by Licensor or its agents. You will not use the External Services in any manner that is inconsistent with the terms of this Custom EULA or that infringes the intellectual property rights of Licensor or any third party. You agree not to use the External Services to harass, abuse, stalk, threaten or defame any person or entity, and that Licensor is not responsible for any such use. External Services may not be available in all languages or in your Home Country, and may not be appropriate or available for use in any particular location. To the extent you choose to use such External Services, you are solely responsible for compliance with any applicable laws. Licensor reserves the right to change, suspend, remove, disable or impose access restrictions or limits on any External Services at any time without notice or liability to you. </p>
                <p>f. NO WARRANTY: YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT USE OF THE LICENSED APPLICATION IS AT YOUR SOLE RISK. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE LICENSED APPLICATION AND ANY SERVICES PERFORMED OR PROVIDED BY THE LICENSED APPLICATION ARE PROVIDED "AS IS" AND "AS AVAILABLE," WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND, AND LICENSOR HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS WITH RESPECT TO THE LICENSED APPLICATION AND ANY SERVICES, EITHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES AND/OR CONDITIONS OF MERCHANTABILITY, OF SATISFACTORY QUALITY, OF FITNESS FOR A PARTICULAR PURPOSE, OF ACCURACY, OF QUIET ENJOYMENT, AND OF NONINFRINGEMENT OF THIRD-PARTY RIGHTS. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY LICENSOR OR ITS AUTHORIZED REPRESENTATIVE SHALL CREATE A WARRANTY. SHOULD THE LICENSED APPLICATION OR SERVICES PROVE DEFECTIVE, YOU ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR, OR CORRECTION. To the extent any warranty exists under law that cannot be disclaimed, Licensor, not Apple, shall be solely responsible for such warranty To the extent you have any claim arising from or relating to your use of the Licensed Application, Licensor, not Apple, is responsible for addressing any such claim, including but not limited to: (i) product liability claims; (ii) any claim that the Licensed Application fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection, privacy or similar legislation. To the extent Licensor is required to provide indemnification by applicable law, Licensor, not Apple, shall be solely responsible for the investigation, defense, settlement and discharge of any claim that the Licensed Application or your use of it infringes any third party intellectual property right.</p>
                <p>g. Limitation of Liability. TO THE EXTENT NOT PROHIBITED BY LAW, IN NO EVENT SHALL LICENSOR BE LIABLE FOR PERSONAL INJURY OR ANY INCIDENTAL, SPECIAL, INDIRECT, OR CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, LOSS OF DATA, BUSINESS INTERRUPTION, OR ANY OTHER COMMERCIAL DAMAGES OR LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OF OR INABILITY TO USE THE LICENSED APPLICATION, HOWEVER CAUSED, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, TORT, OR OTHERWISE) AND EVEN IF LICENSOR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OF LIABILITY FOR PERSONAL INJURY, OR OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THIS LIMITATION MAY NOT APPLY TO YOU. In no event shall Licensor's total liability to you for all damages (other than as may be required by applicable law in cases involving personal injury) exceed the amount of fifty dollars ($50.00). The foregoing limitations will apply even if the above stated remedy fails of its essential purpose.</p>
                <p>h. You may not use or otherwise export or re-export the Licensed Application except as authorized by United States law and the laws of the jurisdiction in which the Licensed Application was obtained. In particular, but without limitation, the Licensed Application may not be exported or re-exported (a) into any U.S.-embargoed countries or (b) to anyone on the U.S. Treasury Department's Specially Designated Nationals List or the U.S. Department of Commerce Denied Persons List or Entity List. By using the Licensed Application, you represent and warrant that you are not located in any such country or on any such list. You also agree that you will not use these products for any purposes prohibited by United States law, including, without limitation, the development, design, manufacture, or production of nuclear, missile, or chemical or biological weapons.</p>
                <p>i. The Licensed Application and related documentation are "Commercial Items", as that term is defined at 48 C.F.R. 2.101, consisting of "Commercial Computer Software" and "Commercial Computer Software Documentation", as such terms are used in 48 C.F.R. 12.212 or 48 C.F.R. 227.7202, as applicable. Consistent with 48 C.F.R. 12.212 or 48 C.F.R. 227.7202-1 through 227.7202-4, as applicable, the Commercial Computer Software and Commercial Computer Software Documentation are being licensed to U.S. Government end users (a) only as Commercial Items and (b) with only those rights as are granted to all other end users pursuant to the terms and conditions herein. Unpublished-rights reserved under the copyright laws of the United States.</p>
                <p>j. You acknowledge and agree that Apple, and Apple's subsidiaries, are third party beneficiaries of the Custom EULA, and that, upon the end-user's acceptance of the terms and conditions of the Custom EULA, Apple will have the right (and will be deemed to have accepted the right) to enforce the Custom EULA against You as a third party beneficiary thereof.</p>
                <p>k. The laws of Switzerland, excluding its conflicts of law rules, govern this license and your use of the Licensed Application. Place of jurisdiction shall be Zurich, Switzerland.</p>

                <p>University of Zurich Contact:</p>

                <p>
                    Datenschutzdelegierter der UZH
                    <br />
                    Stampfenbachstrasse 73
                    <br />
                    CH-8006 Zuerich
                </p>

            </div>
        </div>
    );

}
