const COLORS = {};
const DARK_COLORS = {};

COLORS.PRIMARY_BACKGROUND = '#F7F7F7';
COLORS.PRIMARY_TEXT = '#393E46';
COLORS.PRIMARY_TEXT_MUTED = '#929AAB';
COLORS.CARD_BACKGROUND = '#FFFFFF';
COLORS.CARD_TEXT = '#393E46';
COLORS.CARD_TEXT_MUTED = '#929AAB';
COLORS.ACCENT_BACKGROUND = '#0028a5'
COLORS.ACCENT_TEXT = '#EEEEEE';
COLORS.ERROR_TEXT = 'red'
COLORS.PAGINATION_ACTIVE = '#393E46';
COLORS.PAGINATION_INACTIVE = '#EBDFDF'

DARK_COLORS.PRIMARY_BACKGROUND = '#2D3239';
DARK_COLORS.PRIMARY_TEXT = '#EEEEEE';
DARK_COLORS.PRIMARY_TEXT_MUTED = '#929AAB';
DARK_COLORS.CARD_BACKGROUND = '#222831'
DARK_COLORS.CARD_TEXT = '#EEEEEE';
DARK_COLORS.CARD_TEXT_MUTED = '#929AAB';
DARK_COLORS.ACCENT_BACKGROUND = '#0028a5'
DARK_COLORS.ACCENT_TEXT = '#EEEEEE';
DARK_COLORS.ERROR_TEXT = 'red';
DARK_COLORS.PAGINATION_ACTIVE = '#EEEEEE';
DARK_COLORS.PAGINATION_INACTIVE = '#646975';

export { COLORS, DARK_COLORS };
